// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 健康检查请求
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

// 健康检查响应
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ModelLoaded   bool                   `protobuf:"varint,2,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HealthResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

// 嵌入请求
type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Images        [][]byte               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"` // 图片二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *EmbeddingRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddingRequest) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

// 单个嵌入结果
type EmbeddingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingData) Reset() {
	*x = EmbeddingData{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingData) ProtoMessage() {}

func (x *EmbeddingData) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingData.ProtoReflect.Descriptor instead.
func (*EmbeddingData) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *EmbeddingData) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EmbeddingData) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// 嵌入响应
type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*EmbeddingData       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	PromptTokens  int32                  `protobuf:"varint,3,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingResponse) GetData() []*EmbeddingData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EmbeddingResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddingResponse) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *EmbeddingResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// 美学评分请求
type AestheticRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Images             [][]byte               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`                                                    // 图片二进制数据
	ReturnDistribution bool                   `protobuf:"varint,2,opt,name=return_distribution,json=returnDistribution,proto3" json:"return_distribution,omitempty"` // 是否返回概率分布
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AestheticRequest) Reset() {
	*x = AestheticRequest{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AestheticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AestheticRequest) ProtoMessage() {}

func (x *AestheticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AestheticRequest.ProtoReflect.Descriptor instead.
func (*AestheticRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *AestheticRequest) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *AestheticRequest) GetReturnDistribution() bool {
	if x != nil {
		return x.ReturnDistribution
	}
	return false
}

// 单个美学评分结果
type AestheticData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`                      // 1-10 分
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`                        // 评分等级描述
	Distribution  []float32              `protobuf:"fixed32,4,rep,packed,name=distribution,proto3" json:"distribution,omitempty"` // 10 类概率分布 (可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AestheticData) Reset() {
	*x = AestheticData{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AestheticData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AestheticData) ProtoMessage() {}

func (x *AestheticData) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AestheticData.ProtoReflect.Descriptor instead.
func (*AestheticData) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *AestheticData) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AestheticData) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AestheticData) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *AestheticData) GetDistribution() []float32 {
	if x != nil {
		return x.Distribution
	}
	return nil
}

// 美学评分响应
type AestheticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*AestheticData       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AestheticResponse) Reset() {
	*x = AestheticResponse{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AestheticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AestheticResponse) ProtoMessage() {}

func (x *AestheticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AestheticResponse.ProtoReflect.Descriptor instead.
func (*AestheticResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *AestheticResponse) GetData() []*AestheticData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AestheticResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AestheticResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

// 多模态内容项
type MultimodalContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*MultimodalContent_Text
	//	*MultimodalContent_Image
	Content       isMultimodalContent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultimodalContent) Reset() {
	*x = MultimodalContent{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultimodalContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultimodalContent) ProtoMessage() {}

func (x *MultimodalContent) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultimodalContent.ProtoReflect.Descriptor instead.
func (*MultimodalContent) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *MultimodalContent) GetContent() isMultimodalContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MultimodalContent) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*MultimodalContent_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *MultimodalContent) GetImage() []byte {
	if x != nil {
		if x, ok := x.Content.(*MultimodalContent_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isMultimodalContent_Content interface {
	isMultimodalContent_Content()
}

type MultimodalContent_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MultimodalContent_Image struct {
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3,oneof"` // 图片二进制数据
}

func (*MultimodalContent_Text) isMultimodalContent_Content() {}

func (*MultimodalContent_Image) isMultimodalContent_Content() {}

// 多模态嵌入请求
type MultimodalEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Contents      []*MultimodalContent   `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultimodalEmbeddingRequest) Reset() {
	*x = MultimodalEmbeddingRequest{}
	mi := &file_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultimodalEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultimodalEmbeddingRequest) ProtoMessage() {}

func (x *MultimodalEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultimodalEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*MultimodalEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{9}
}

func (x *MultimodalEmbeddingRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *MultimodalEmbeddingRequest) GetContents() []*MultimodalContent {
	if x != nil {
		return x.Contents
	}
	return nil
}

// 单个多模态嵌入结果
type MultimodalEmbeddingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "text" 或 "image"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultimodalEmbeddingItem) Reset() {
	*x = MultimodalEmbeddingItem{}
	mi := &file_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultimodalEmbeddingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultimodalEmbeddingItem) ProtoMessage() {}

func (x *MultimodalEmbeddingItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultimodalEmbeddingItem.ProtoReflect.Descriptor instead.
func (*MultimodalEmbeddingItem) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{10}
}

func (x *MultimodalEmbeddingItem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MultimodalEmbeddingItem) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *MultimodalEmbeddingItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 多模态嵌入响应
type MultimodalEmbeddingResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Embeddings    []*MultimodalEmbeddingItem `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	Model         string                     `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	InputTokens   int32                      `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	ImageTokens   int32                      `protobuf:"varint,4,opt,name=image_tokens,json=imageTokens,proto3" json:"image_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultimodalEmbeddingResponse) Reset() {
	*x = MultimodalEmbeddingResponse{}
	mi := &file_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultimodalEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultimodalEmbeddingResponse) ProtoMessage() {}

func (x *MultimodalEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultimodalEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*MultimodalEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{11}
}

func (x *MultimodalEmbeddingResponse) GetEmbeddings() []*MultimodalEmbeddingItem {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *MultimodalEmbeddingResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *MultimodalEmbeddingResponse) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *MultimodalEmbeddingResponse) GetImageTokens() int32 {
	if x != nil {
		return x.ImageTokens
	}
	return 0
}

// HDBSCAN 参数配置
type HDBSCANParams struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MinClusterSize          int32                  `protobuf:"varint,1,opt,name=min_cluster_size,json=minClusterSize,proto3" json:"min_cluster_size,omitempty"`
	MinSamples              *int32                 `protobuf:"varint,2,opt,name=min_samples,json=minSamples,proto3,oneof" json:"min_samples,omitempty"`
	ClusterSelectionEpsilon float32                `protobuf:"fixed32,3,opt,name=cluster_selection_epsilon,json=clusterSelectionEpsilon,proto3" json:"cluster_selection_epsilon,omitempty"`
	ClusterSelectionMethod  string                 `protobuf:"bytes,4,opt,name=cluster_selection_method,json=clusterSelectionMethod,proto3" json:"cluster_selection_method,omitempty"`
	Metric                  string                 `protobuf:"bytes,5,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HDBSCANParams) Reset() {
	*x = HDBSCANParams{}
	mi := &file_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HDBSCANParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDBSCANParams) ProtoMessage() {}

func (x *HDBSCANParams) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDBSCANParams.ProtoReflect.Descriptor instead.
func (*HDBSCANParams) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{12}
}

func (x *HDBSCANParams) GetMinClusterSize() int32 {
	if x != nil {
		return x.MinClusterSize
	}
	return 0
}

func (x *HDBSCANParams) GetMinSamples() int32 {
	if x != nil && x.MinSamples != nil {
		return *x.MinSamples
	}
	return 0
}

func (x *HDBSCANParams) GetClusterSelectionEpsilon() float32 {
	if x != nil {
		return x.ClusterSelectionEpsilon
	}
	return 0
}

func (x *HDBSCANParams) GetClusterSelectionMethod() string {
	if x != nil {
		return x.ClusterSelectionMethod
	}
	return ""
}

func (x *HDBSCANParams) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

// UMAP 降维参数
type UMAPParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	NComponents   int32                  `protobuf:"varint,2,opt,name=n_components,json=nComponents,proto3" json:"n_components,omitempty"`
	NNeighbors    int32                  `protobuf:"varint,3,opt,name=n_neighbors,json=nNeighbors,proto3" json:"n_neighbors,omitempty"`
	MinDist       float32                `protobuf:"fixed32,4,opt,name=min_dist,json=minDist,proto3" json:"min_dist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UMAPParams) Reset() {
	*x = UMAPParams{}
	mi := &file_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UMAPParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UMAPParams) ProtoMessage() {}

func (x *UMAPParams) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UMAPParams.ProtoReflect.Descriptor instead.
func (*UMAPParams) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{13}
}

func (x *UMAPParams) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UMAPParams) GetNComponents() int32 {
	if x != nil {
		return x.NComponents
	}
	return 0
}

func (x *UMAPParams) GetNNeighbors() int32 {
	if x != nil {
		return x.NNeighbors
	}
	return 0
}

func (x *UMAPParams) GetMinDist() float32 {
	if x != nil {
		return x.MinDist
	}
	return 0
}

// 嵌入向量
type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{14}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// 聚类请求
type ClusteringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	ImageIds      []int64                `protobuf:"varint,2,rep,packed,name=image_ids,json=imageIds,proto3" json:"image_ids,omitempty"`
	HdbscanParams *HDBSCANParams         `protobuf:"bytes,3,opt,name=hdbscan_params,json=hdbscanParams,proto3" json:"hdbscan_params,omitempty"`
	UmapParams    *UMAPParams            `protobuf:"bytes,4,opt,name=umap_params,json=umapParams,proto3" json:"umap_params,omitempty"`
	TaskId        int64                  `protobuf:"varint,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 调用方任务 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusteringRequest) Reset() {
	*x = ClusteringRequest{}
	mi := &file_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusteringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusteringRequest) ProtoMessage() {}

func (x *ClusteringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusteringRequest.ProtoReflect.Descriptor instead.
func (*ClusteringRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{15}
}

func (x *ClusteringRequest) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *ClusteringRequest) GetImageIds() []int64 {
	if x != nil {
		return x.ImageIds
	}
	return nil
}

func (x *ClusteringRequest) GetHdbscanParams() *HDBSCANParams {
	if x != nil {
		return x.HdbscanParams
	}
	return nil
}

func (x *ClusteringRequest) GetUmapParams() *UMAPParams {
	if x != nil {
		return x.UmapParams
	}
	return nil
}

func (x *ClusteringRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

// 单个聚类结果
type ClusterResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClusterId      int32                  `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ImageIds       []int64                `protobuf:"varint,2,rep,packed,name=image_ids,json=imageIds,proto3" json:"image_ids,omitempty"`
	AvgProbability float32                `protobuf:"fixed32,3,opt,name=avg_probability,json=avgProbability,proto3" json:"avg_probability,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterResult) Reset() {
	*x = ClusterResult{}
	mi := &file_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterResult) ProtoMessage() {}

func (x *ClusterResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterResult.ProtoReflect.Descriptor instead.
func (*ClusterResult) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{16}
}

func (x *ClusterResult) GetClusterId() int32 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *ClusterResult) GetImageIds() []int64 {
	if x != nil {
		return x.ImageIds
	}
	return nil
}

func (x *ClusterResult) GetAvgProbability() float32 {
	if x != nil {
		return x.AvgProbability
	}
	return 0
}

// 聚类响应
type ClusteringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*ClusterResult       `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	NoiseImageIds []int64                `protobuf:"varint,2,rep,packed,name=noise_image_ids,json=noiseImageIds,proto3" json:"noise_image_ids,omitempty"`
	NClusters     int32                  `protobuf:"varint,3,opt,name=n_clusters,json=nClusters,proto3" json:"n_clusters,omitempty"`
	ParamsUsed    map[string]string      `protobuf:"bytes,4,rep,name=params_used,json=paramsUsed,proto3" json:"params_used,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusteringResponse) Reset() {
	*x = ClusteringResponse{}
	mi := &file_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusteringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusteringResponse) ProtoMessage() {}

func (x *ClusteringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusteringResponse.ProtoReflect.Descriptor instead.
func (*ClusteringResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{17}
}

func (x *ClusteringResponse) GetClusters() []*ClusterResult {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ClusteringResponse) GetNoiseImageIds() []int64 {
	if x != nil {
		return x.NoiseImageIds
	}
	return nil
}

func (x *ClusteringResponse) GetNClusters() int32 {
	if x != nil {
		return x.NClusters
	}
	return 0
}

func (x *ClusteringResponse) GetParamsUsed() map[string]string {
	if x != nil {
		return x.ParamsUsed
	}
	return nil
}

// 进度更新消息 (用于流式响应)
type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`      // pending | clustering | completed | failed
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"` // 0-100
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Result        *ClusteringResponse    `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"` // 仅在完成时填充
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`   // 仅在失败时填充
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_ai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{18}
}

func (x *ProgressUpdate) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ProgressUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProgressUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetResult() *ClusteringResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProgressUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"\x0f\n" +
	"\rHealthRequest\"}\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fmodel_loaded\x18\x02 \x01(\bR\vmodelLoaded\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\"@\n" +
	"\x10EmbeddingRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06images\x18\x02 \x03(\fR\x06images\"C\n" +
	"\rEmbeddingData\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\"\x98\x01\n" +
	"\x11EmbeddingResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.ai.EmbeddingDataR\x04data\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rprompt_tokens\x18\x03 \x01(\x05R\fpromptTokens\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\"[\n" +
	"\x10AestheticRequest\x12\x16\n" +
	"\x06images\x18\x01 \x03(\fR\x06images\x12/\n" +
	"\x13return_distribution\x18\x02 \x01(\bR\x12returnDistribution\"u\n" +
	"\rAestheticData\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\"\n" +
	"\fdistribution\x18\x04 \x03(\x02R\fdistribution\"j\n" +
	"\x11AestheticResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.ai.AestheticDataR\x04data\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\"L\n" +
	"\x11MultimodalContent\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x16\n" +
	"\x05image\x18\x02 \x01(\fH\x00R\x05imageB\t\n" +
	"\acontent\"e\n" +
	"\x1aMultimodalEmbeddingRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x121\n" +
	"\bcontents\x18\x02 \x03(\v2\x15.ai.MultimodalContentR\bcontents\"a\n" +
	"\x17MultimodalEmbeddingItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xb6\x01\n" +
	"\x1bMultimodalEmbeddingResponse\x12;\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x1b.ai.MultimodalEmbeddingItemR\n" +
	"embeddings\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x05R\vinputTokens\x12!\n" +
	"\fimage_tokens\x18\x04 \x01(\x05R\vimageTokens\"\xfd\x01\n" +
	"\rHDBSCANParams\x12(\n" +
	"\x10min_cluster_size\x18\x01 \x01(\x05R\x0eminClusterSize\x12$\n" +
	"\vmin_samples\x18\x02 \x01(\x05H\x00R\n" +
	"minSamples\x88\x01\x01\x12:\n" +
	"\x19cluster_selection_epsilon\x18\x03 \x01(\x02R\x17clusterSelectionEpsilon\x128\n" +
	"\x18cluster_selection_method\x18\x04 \x01(\tR\x16clusterSelectionMethod\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\tR\x06metricB\x0e\n" +
	"\f_min_samples\"\x85\x01\n" +
	"\n" +
	"UMAPParams\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\fn_components\x18\x02 \x01(\x05R\vnComponents\x12\x1f\n" +
	"\vn_neighbors\x18\x03 \x01(\x05R\n" +
	"nNeighbors\x12\x19\n" +
	"\bmin_dist\x18\x04 \x01(\x02R\aminDist\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\xe3\x01\n" +
	"\x11ClusteringRequest\x12-\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\r.ai.EmbeddingR\n" +
	"embeddings\x12\x1b\n" +
	"\timage_ids\x18\x02 \x03(\x03R\bimageIds\x128\n" +
	"\x0ehdbscan_params\x18\x03 \x01(\v2\x11.ai.HDBSCANParamsR\rhdbscanParams\x12/\n" +
	"\vumap_params\x18\x04 \x01(\v2\x0e.ai.UMAPParamsR\n" +
	"umapParams\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\x03R\x06taskId\"t\n" +
	"\rClusterResult\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x05R\tclusterId\x12\x1b\n" +
	"\timage_ids\x18\x02 \x03(\x03R\bimageIds\x12'\n" +
	"\x0favg_probability\x18\x03 \x01(\x02R\x0eavgProbability\"\x92\x02\n" +
	"\x12ClusteringResponse\x12-\n" +
	"\bclusters\x18\x01 \x03(\v2\x11.ai.ClusterResultR\bclusters\x12&\n" +
	"\x0fnoise_image_ids\x18\x02 \x03(\x03R\rnoiseImageIds\x12\x1d\n" +
	"\n" +
	"n_clusters\x18\x03 \x01(\x05R\tnClusters\x12G\n" +
	"\vparams_used\x18\x04 \x03(\v2&.ai.ClusteringResponse.ParamsUsedEntryR\n" +
	"paramsUsed\x1a=\n" +
	"\x0fParamsUsedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\x0eProgressUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12.\n" +
	"\x06result\x18\x05 \x01(\v2\x16.ai.ClusteringResponseR\x06result\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\xda\x02\n" +
	"\tAIService\x12/\n" +
	"\x06Health\x12\x11.ai.HealthRequest\x1a\x12.ai.HealthResponse\x12>\n" +
	"\x0fCreateEmbedding\x12\x14.ai.EmbeddingRequest\x1a\x15.ai.EmbeddingResponse\x12@\n" +
	"\x11EvaluateAesthetic\x12\x14.ai.AestheticRequest\x1a\x15.ai.AestheticResponse\x12\\\n" +
	"\x19CreateMultimodalEmbedding\x12\x1e.ai.MultimodalEmbeddingRequest\x1a\x1f.ai.MultimodalEmbeddingResponse\x12<\n" +
	"\rClusterStream\x12\x15.ai.ClusteringRequest\x1a\x12.ai.ProgressUpdate0\x01B\x1dZ\x1bgithub.com/gallery/proto/aib\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_ai_proto_goTypes = []any{
	(*HealthRequest)(nil),               // 0: ai.HealthRequest
	(*HealthResponse)(nil),              // 1: ai.HealthResponse
	(*EmbeddingRequest)(nil),            // 2: ai.EmbeddingRequest
	(*EmbeddingData)(nil),               // 3: ai.EmbeddingData
	(*EmbeddingResponse)(nil),           // 4: ai.EmbeddingResponse
	(*AestheticRequest)(nil),            // 5: ai.AestheticRequest
	(*AestheticData)(nil),               // 6: ai.AestheticData
	(*AestheticResponse)(nil),           // 7: ai.AestheticResponse
	(*MultimodalContent)(nil),           // 8: ai.MultimodalContent
	(*MultimodalEmbeddingRequest)(nil),  // 9: ai.MultimodalEmbeddingRequest
	(*MultimodalEmbeddingItem)(nil),     // 10: ai.MultimodalEmbeddingItem
	(*MultimodalEmbeddingResponse)(nil), // 11: ai.MultimodalEmbeddingResponse
	(*HDBSCANParams)(nil),               // 12: ai.HDBSCANParams
	(*UMAPParams)(nil),                  // 13: ai.UMAPParams
	(*Embedding)(nil),                   // 14: ai.Embedding
	(*ClusteringRequest)(nil),           // 15: ai.ClusteringRequest
	(*ClusterResult)(nil),               // 16: ai.ClusterResult
	(*ClusteringResponse)(nil),          // 17: ai.ClusteringResponse
	(*ProgressUpdate)(nil),              // 18: ai.ProgressUpdate
	nil,                                 // 19: ai.ClusteringResponse.ParamsUsedEntry
}
var file_ai_proto_depIdxs = []int32{
	3,  // 0: ai.EmbeddingResponse.data:type_name -> ai.EmbeddingData
	6,  // 1: ai.AestheticResponse.data:type_name -> ai.AestheticData
	8,  // 2: ai.MultimodalEmbeddingRequest.contents:type_name -> ai.MultimodalContent
	10, // 3: ai.MultimodalEmbeddingResponse.embeddings:type_name -> ai.MultimodalEmbeddingItem
	14, // 4: ai.ClusteringRequest.embeddings:type_name -> ai.Embedding
	12, // 5: ai.ClusteringRequest.hdbscan_params:type_name -> ai.HDBSCANParams
	13, // 6: ai.ClusteringRequest.umap_params:type_name -> ai.UMAPParams
	16, // 7: ai.ClusteringResponse.clusters:type_name -> ai.ClusterResult
	19, // 8: ai.ClusteringResponse.params_used:type_name -> ai.ClusteringResponse.ParamsUsedEntry
	17, // 9: ai.ProgressUpdate.result:type_name -> ai.ClusteringResponse
	0,  // 10: ai.AIService.Health:input_type -> ai.HealthRequest
	2,  // 11: ai.AIService.CreateEmbedding:input_type -> ai.EmbeddingRequest
	5,  // 12: ai.AIService.EvaluateAesthetic:input_type -> ai.AestheticRequest
	9,  // 13: ai.AIService.CreateMultimodalEmbedding:input_type -> ai.MultimodalEmbeddingRequest
	15, // 14: ai.AIService.ClusterStream:input_type -> ai.ClusteringRequest
	1,  // 15: ai.AIService.Health:output_type -> ai.HealthResponse
	4,  // 16: ai.AIService.CreateEmbedding:output_type -> ai.EmbeddingResponse
	7,  // 17: ai.AIService.EvaluateAesthetic:output_type -> ai.AestheticResponse
	11, // 18: ai.AIService.CreateMultimodalEmbedding:output_type -> ai.MultimodalEmbeddingResponse
	18, // 19: ai.AIService.ClusterStream:output_type -> ai.ProgressUpdate
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	file_ai_proto_msgTypes[8].OneofWrappers = []any{
		(*MultimodalContent_Text)(nil),
		(*MultimodalContent_Image)(nil),
	}
	file_ai_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
