// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_Health_FullMethodName                    = "/ai.AIService/Health"
	AIService_CreateEmbedding_FullMethodName           = "/ai.AIService/CreateEmbedding"
	AIService_EvaluateAesthetic_FullMethodName         = "/ai.AIService/EvaluateAesthetic"
	AIService_CreateMultimodalEmbedding_FullMethodName = "/ai.AIService/CreateMultimodalEmbedding"
	AIService_ClusterStream_FullMethodName             = "/ai.AIService/ClusterStream"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 原有服务（保留用于直接调用场景）
type AIServiceClient interface {
	// 健康检查
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// 图片嵌入
	CreateEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	// 美学评分
	EvaluateAesthetic(ctx context.Context, in *AestheticRequest, opts ...grpc.CallOption) (*AestheticResponse, error)
	// 多模态嵌入 (文本+图片)
	CreateMultimodalEmbedding(ctx context.Context, in *MultimodalEmbeddingRequest, opts ...grpc.CallOption) (*MultimodalEmbeddingResponse, error)
	// 流式聚类 - 返回进度更新流
	ClusterStream(ctx context.Context, in *ClusteringRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AIService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) CreateEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, AIService_CreateEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) EvaluateAesthetic(ctx context.Context, in *AestheticRequest, opts ...grpc.CallOption) (*AestheticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AestheticResponse)
	err := c.cc.Invoke(ctx, AIService_EvaluateAesthetic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) CreateMultimodalEmbedding(ctx context.Context, in *MultimodalEmbeddingRequest, opts ...grpc.CallOption) (*MultimodalEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultimodalEmbeddingResponse)
	err := c.cc.Invoke(ctx, AIService_CreateMultimodalEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ClusterStream(ctx context.Context, in *ClusteringRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[0], AIService_ClusterStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClusteringRequest, ProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ClusterStreamClient = grpc.ServerStreamingClient[ProgressUpdate]

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
//
// 原有服务（保留用于直接调用场景）
type AIServiceServer interface {
	// 健康检查
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// 图片嵌入
	CreateEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	// 美学评分
	EvaluateAesthetic(context.Context, *AestheticRequest) (*AestheticResponse, error)
	// 多模态嵌入 (文本+图片)
	CreateMultimodalEmbedding(context.Context, *MultimodalEmbeddingRequest) (*MultimodalEmbeddingResponse, error)
	// 流式聚类 - 返回进度更新流
	ClusterStream(*ClusteringRequest, grpc.ServerStreamingServer[ProgressUpdate]) error
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAIServiceServer) CreateEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEmbedding not implemented")
}
func (UnimplementedAIServiceServer) EvaluateAesthetic(context.Context, *AestheticRequest) (*AestheticResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateAesthetic not implemented")
}
func (UnimplementedAIServiceServer) CreateMultimodalEmbedding(context.Context, *MultimodalEmbeddingRequest) (*MultimodalEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMultimodalEmbedding not implemented")
}
func (UnimplementedAIServiceServer) ClusterStream(*ClusteringRequest, grpc.ServerStreamingServer[ProgressUpdate]) error {
	return status.Error(codes.Unimplemented, "method ClusterStream not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_CreateEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).CreateEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_CreateEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).CreateEmbedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_EvaluateAesthetic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AestheticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).EvaluateAesthetic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_EvaluateAesthetic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).EvaluateAesthetic(ctx, req.(*AestheticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_CreateMultimodalEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultimodalEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).CreateMultimodalEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_CreateMultimodalEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).CreateMultimodalEmbedding(ctx, req.(*MultimodalEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ClusterStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClusteringRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).ClusterStream(m, &grpc.GenericServerStream[ClusteringRequest, ProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIService_ClusterStreamServer = grpc.ServerStreamingServer[ProgressUpdate]

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AIService_Health_Handler,
		},
		{
			MethodName: "CreateEmbedding",
			Handler:    _AIService_CreateEmbedding_Handler,
		},
		{
			MethodName: "EvaluateAesthetic",
			Handler:    _AIService_EvaluateAesthetic_Handler,
		},
		{
			MethodName: "CreateMultimodalEmbedding",
			Handler:    _AIService_CreateMultimodalEmbedding_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClusterStream",
			Handler:       _AIService_ClusterStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai.proto",
}
