# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """============== AI 服务定义 ==============

    原有服务（保留用于直接调用场景）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/ai.AIService/Health',
                request_serializer=ai__pb2.HealthRequest.SerializeToString,
                response_deserializer=ai__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.CreateEmbedding = channel.unary_unary(
                '/ai.AIService/CreateEmbedding',
                request_serializer=ai__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=ai__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.EvaluateAesthetic = channel.unary_unary(
                '/ai.AIService/EvaluateAesthetic',
                request_serializer=ai__pb2.AestheticRequest.SerializeToString,
                response_deserializer=ai__pb2.AestheticResponse.FromString,
                _registered_method=True)
        self.CreateMultimodalEmbedding = channel.unary_unary(
                '/ai.AIService/CreateMultimodalEmbedding',
                request_serializer=ai__pb2.MultimodalEmbeddingRequest.SerializeToString,
                response_deserializer=ai__pb2.MultimodalEmbeddingResponse.FromString,
                _registered_method=True)
        self.ClusterStream = channel.unary_stream(
                '/ai.AIService/ClusterStream',
                request_serializer=ai__pb2.ClusteringRequest.SerializeToString,
                response_deserializer=ai__pb2.ProgressUpdate.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """============== AI 服务定义 ==============

    原有服务（保留用于直接调用场景）
    """

    def Health(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEmbedding(self, request, context):
        """图片嵌入
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateAesthetic(self, request, context):
        """美学评分
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMultimodalEmbedding(self, request, context):
        """多模态嵌入 (文本+图片)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClusterStream(self, request, context):
        """流式聚类 - 返回进度更新流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ai__pb2.HealthRequest.FromString,
                    response_serializer=ai__pb2.HealthResponse.SerializeToString,
            ),
            'CreateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmbedding,
                    request_deserializer=ai__pb2.EmbeddingRequest.FromString,
                    response_serializer=ai__pb2.EmbeddingResponse.SerializeToString,
            ),
            'EvaluateAesthetic': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateAesthetic,
                    request_deserializer=ai__pb2.AestheticRequest.FromString,
                    response_serializer=ai__pb2.AestheticResponse.SerializeToString,
            ),
            'CreateMultimodalEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMultimodalEmbedding,
                    request_deserializer=ai__pb2.MultimodalEmbeddingRequest.FromString,
                    response_serializer=ai__pb2.MultimodalEmbeddingResponse.SerializeToString,
            ),
            'ClusterStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ClusterStream,
                    request_deserializer=ai__pb2.ClusteringRequest.FromString,
                    response_serializer=ai__pb2.ProgressUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """============== AI 服务定义 ==============

    原有服务（保留用于直接调用场景）
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/Health',
            ai__pb2.HealthRequest.SerializeToString,
            ai__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/CreateEmbedding',
            ai__pb2.EmbeddingRequest.SerializeToString,
            ai__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateAesthetic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/EvaluateAesthetic',
            ai__pb2.AestheticRequest.SerializeToString,
            ai__pb2.AestheticResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMultimodalEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/CreateMultimodalEmbedding',
            ai__pb2.MultimodalEmbeddingRequest.SerializeToString,
            ai__pb2.MultimodalEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClusterStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.AIService/ClusterStream',
            ai__pb2.ClusteringRequest.SerializeToString,
            ai__pb2.ProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
